In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

1.14.0


In [11]:
hello = tf.constant("Hello ")

In [12]:
world = tf.constant("World")

In [13]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [14]:
print(hello)

Tensor("Const_2:0", shape=(), dtype=string)


In [15]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [16]:
print(result)

b'Hello World'


In [17]:
a = tf.constant(10)

In [18]:
b = tf.constant(20)

In [19]:
type(a)

tensorflow.python.framework.ops.Tensor

In [20]:
a+b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [21]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [22]:
print(result)

30


In [23]:
type(result)

numpy.int32

In [24]:
const = tf.constant(10)

In [31]:
fill_mat = tf.fill((4,4),10)

In [32]:
myzeros = tf.zeros((4,4))

In [33]:
myones = tf.ones((4,4))

In [35]:
myrand = tf.random_normal((4,4),mean=0,stddev=1.0)

In [36]:
myrandu = tf.random_uniform((4,4),minval = 0, maxval=1)

In [37]:
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [38]:
my_ops = [const,fill_mat,myzeros,myones,myrand,myrandu]

In [39]:
sess = tf.InteractiveSession()

In [42]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.66684026 -0.4796542   0.8711453  -0.5955296 ]
 [ 0.253433    1.5742558  -0.9669341  -0.92339087]
 [-1.0127019  -0.05233038  1.0537612  -0.21142165]
 [-0.03898315 -0.89274216  0.57253367  1.4746442 ]]


[[0.13015795 0.33094943 0.70104504 0.5758668 ]
 [0.6213068  0.6978915  0.73639834 0.11194003]
 [0.31993914 0.17583787 0.998374   0.87137914]
 [0.13174832 0.00620258 0.9802817  0.6550158 ]]




In [43]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.00983016  0.09458464 -0.3970103  -1.513761  ]
 [ 0.7739051   0.3042761  -0.9690888   0.50454813]
 [-1.6831852   1.1730648   0.07876197  0.64167863]
 [-0.63559943 -0.21023352 -0.21813142  0.60542053]]


[[0.30210853 0.83119893 0.6372006  0.19838834]
 [0.11865675 0.6100116  0.69255805 0.20903802]
 [0.9506084  0.22667718 0.07954681 0.54038465]
 [0.965425   0.60981274 0.3094051  0.11502302]]




In [44]:
a = tf.constant([[1,2],[3,4]])

In [45]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [47]:
b = tf.constant([[10],[100]])

In [49]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [50]:
result = tf.matmul(a,b)

In [51]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [52]:
result.eval()

array([[210],
       [430]], dtype=int32)