In [9]:
import numpy as np

In [10]:
from sklearn.preprocessing import MinMaxScaler #See spelling of scaler

In [11]:
data = np.random.randint(0,100,(10,2))

In [12]:
data

array([[ 2, 46],
       [55, 22],
       [49, 83],
       [63, 46],
       [54, 75],
       [ 8, 50],
       [21, 93],
       [95, 60],
       [54,  1],
       [35, 52]])

In [13]:
scaler_model = MinMaxScaler()

In [14]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [15]:
scaler_model.fit(data)

/home/akhil/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [19]:
scaler_model.transform(data) #Normalizes each column

array([[0.        , 0.48913043],
       [0.56989247, 0.22826087],
       [0.50537634, 0.89130435],
       [0.65591398, 0.48913043],
       [0.55913978, 0.80434783],
       [0.06451613, 0.5326087 ],
       [0.20430108, 1.        ],
       [1.        , 0.64130435],
       [0.55913978, 0.        ],
       [0.35483871, 0.55434783]])

In [20]:
scaler_model.fit_transform(data)

/home/akhil/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.        , 0.48913043],
       [0.56989247, 0.22826087],
       [0.50537634, 0.89130435],
       [0.65591398, 0.48913043],
       [0.55913978, 0.80434783],
       [0.06451613, 0.5326087 ],
       [0.20430108, 1.        ],
       [1.        , 0.64130435],
       [0.55913978, 0.        ],
       [0.35483871, 0.55434783]])

In [23]:
import pandas as pd

In [27]:
mydata = np.random.randint(0,101,(50,4))

In [28]:
mydata

array([[73, 66, 32, 50],
       [60,  7, 16, 24],
       [43, 34, 28, 37],
       [ 6, 21, 20, 12],
       [79, 90, 57, 71],
       [26, 54, 52, 34],
       [16, 98, 12, 63],
       [22, 55,  2, 53],
       [72, 59,  4,  9],
       [36, 96, 28, 91],
       [95, 78, 70, 28],
       [63, 63, 98, 36],
       [21, 13, 84, 59],
       [90, 39, 84, 25],
       [94, 56, 13, 81],
       [11,  3, 81, 85],
       [18, 24, 69, 19],
       [58, 47, 49, 32],
       [52, 78, 12, 95],
       [82, 75, 68, 63],
       [36, 43, 50,  0],
       [41, 74, 53, 91],
       [26, 54, 28, 64],
       [45, 98, 99, 78],
       [39, 81, 41, 45],
       [86, 59, 33, 75],
       [99, 20, 11, 86],
       [42, 11, 33, 90],
       [95, 25, 50,  0],
       [79, 84, 41, 78],
       [74, 86, 52, 26],
       [44, 94, 74, 44],
       [ 2, 73, 13, 55],
       [72, 79, 60, 10],
       [96, 93, 74, 70],
       [57, 34, 79, 75],
       [93,  3, 50, 22],
       [ 6, 64, 98, 89],
       [ 7, 90, 51, 73],
       [52, 54, 60, 87],


In [33]:
df = pd.DataFrame(data = mydata,columns =['f1','f2','f3','label'] )

In [34]:
df

f1  f2  f3  label
0   73  66  32     50
1   60   7  16     24
2   43  34  28     37
3    6  21  20     12
4   79  90  57     71
5   26  54  52     34
6   16  98  12     63
7   22  55   2     53
8   72  59   4      9
9   36  96  28     91
10  95  78  70     28
11  63  63  98     36
12  21  13  84     59
13  90  39  84     25
14  94  56  13     81
15  11   3  81     85
16  18  24  69     19
17  58  47  49     32
18  52  78  12     95
19  82  75  68     63
20  36  43  50      0
21  41  74  53     91
22  26  54  28     64
23  45  98  99     78
24  39  81  41     45
25  86  59  33     75
26  99  20  11     86
27  42  11  33     90
28  95  25  50      0
29  79  84  41     78
30  74  86  52     26
31  44  94  74     44
32   2  73  13     55
33  72  79  60     10
34  96  93  74     70
35  57  34  79     75
36  93   3  50     22
37   6  64  98     89
38   7  90  51     73
39  52  54  60     87
40  93  17  98     38
41  51  52  49     53
42  23  94  97      0
43  76  20  83     57
44   6  31  44     45
45  48  33   9      3
46  51  94  48     51
47  54  99  26     55
48  31  94   9      2
49  62  39  47      2

In [35]:
X = df[['f1','f2','f3']]

In [36]:
X

f1  f2  f3
0   73  66  32
1   60   7  16
2   43  34  28
3    6  21  20
4   79  90  57
5   26  54  52
6   16  98  12
7   22  55   2
8   72  59   4
9   36  96  28
10  95  78  70
11  63  63  98
12  21  13  84
13  90  39  84
14  94  56  13
15  11   3  81
16  18  24  69
17  58  47  49
18  52  78  12
19  82  75  68
20  36  43  50
21  41  74  53
22  26  54  28
23  45  98  99
24  39  81  41
25  86  59  33
26  99  20  11
27  42  11  33
28  95  25  50
29  79  84  41
30  74  86  52
31  44  94  74
32   2  73  13
33  72  79  60
34  96  93  74
35  57  34  79
36  93   3  50
37   6  64  98
38   7  90  51
39  52  54  60
40  93  17  98
41  51  52  49
42  23  94  97
43  76  20  83
44   6  31  44
45  48  33   9
46  51  94  48
47  54  99  26
48  31  94   9
49  62  39  47

In [39]:
y = df['label']

In [38]:
y

0     50
1     24
2     37
3     12
4     71
5     34
6     63
7     53
8      9
9     91
10    28
11    36
12    59
13    25
14    81
15    85
16    19
17    32
18    95
19    63
20     0
21    91
22    64
23    78
24    45
25    75
26    86
27    90
28     0
29    78
30    26
31    44
32    55
33    10
34    70
35    75
36    22
37    89
38    73
39    87
40    38
41    53
42     0
43    57
44    45
45     3
46    51
47    55
48     2
49     2
Name: label, dtype: int64

In [40]:
from sklearn.model_selection import train_test_split

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=101)

In [45]:
#X is features, y is label, test size is % of the entire set, random state is for repeatability

In [47]:
X_train.shape

(33, 3)

In [48]:
X_test.shape

(17, 3)